{{- if .Values.configServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: config-server    # Đây là tên alias mà app cần
  labels:
    app: config-server-alias
spec:
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: spring-petclinic-config-server
{{- end }}
