{{- if .Values.gateway.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-api-gateway
  labels:
    app: spring-petclinic-api-gateway
spec:
  replicas: {{ .Values.gateway.replicaCount | default .Values.global.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: spring-petclinic-api-gateway
  template:
    metadata:
      labels:
        app: spring-petclinic-api-gateway
    spec:
      containers:
        - name: spring-petclinic-api-gateway
          image: "{{ .Values.global.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8080
          {{- if .Values.gateway.env }}
          env:
            {{- range $key, $value := .Values.gateway.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-api-gateway
  labels:
    app: spring-petclinic-api-gateway
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.gateway.service.nodePort }}
  selector:
    app: spring-petclinic-api-gateway
{{- end }}
