{{- if .Values.tracingServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-tracing-server
  labels:
    app: spring-petclinic-tracing-server
spec:
  replicas: {{ .Values.tracingServer.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: spring-petclinic-tracing-server
  template:
    metadata:
      labels:
        app: spring-petclinic-tracing-server
    spec:
      containers:
        - name: spring-petclinic-tracing-server
          image: "{{ .Values.tracingServer.image.repository }}:{{ .Values.tracingServer.image.tag }}"
          imagePullPolicy: {{ .Values.tracingServer.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 9411
          {{- if .Values.tracingServer.env }}
          env:
            {{- range $key, $val := .Values.tracingServer.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-tracing-server
  labels:
    app: spring-petclinic-tracing-server
spec:
  type: ClusterIP
  ports:
    - port: 9411
      targetPort: 9411
  selector:
    app: spring-petclinic-tracing-server
{{- end }}
