{{- if .Values.configServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-config-server
  labels:
    app: spring-petclinic-config-server
spec:
  replicas: {{ .Values.configServer.replicaCount | default .Values.global.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: spring-petclinic-config-server
  template:
    metadata:
      labels:
        app: spring-petclinic-config-server
    spec:
      containers:
        - name: spring-petclinic-config-server
          image: "{{ .Values.global.image.repository }}:{{ .Values.configServer.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8888
          {{- if .Values.configServer.env }}
          env:
            {{- range $key, $value := .Values.configServer.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-config-server
  labels:
    app: spring-petclinic-config-server
spec:
  type: ClusterIP
  selector:
    app: spring-petclinic-config-server
  ports:
    - port: 8888
      targetPort: 8888
{{- end }}
