{{- if .Values.discoveryServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-discovery-server
  labels:
    app: spring-petclinic-discovery-server
spec:
  replicas: {{ .Values.discoveryServer.replicaCount | default .Values.global.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: spring-petclinic-discovery-server
  template:
    metadata:
      labels:
        app: spring-petclinic-discovery-server
    spec:
      containers:
        - name: spring-petclinic-discovery-server
          image: "{{ .Values.global.image.repository }}:{{ .Values.discoveryServer.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8761
          {{- if .Values.discoveryServer.env }}
          env:
            {{- range $key, $val := .Values.discoveryServer.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-discovery-server
  labels:
    app: spring-petclinic-discovery-server
spec:
  type: ClusterIP
  selector:
    app: spring-petclinic-discovery-server
  ports:
    - port: 8761
      targetPort: 8761
{{- end }}
