{{- if .Values.adminServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-admin-server
spec:
  replicas: {{ .Values.adminServer.replicaCount | default 1 }}
  template:
    spec:
      containers:
      - name: admin
        image: "{{ .Values.global.image.repository }}-spring-petclinic-admin-server:{{ .Values.adminServer.image.tag }}"
        ports:
        - containerPort: 9090
{{- if .Values.adminServer.env }}
        env:
        {{- range $key, $val := .Values.adminServer.env }}
        - name: {{ $key }}
          value: {{ $val | quote }}
        {{- end }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-admin-server
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: {{ .Values.adminServer.service.nodePort }}
{{- end }}
