{{- if .Values.customers.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-customers-service
  labels:
    app: spring-petclinic-customers-service
spec:
  replicas: {{ .Values.customers.replicaCount | default .Values.global.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: spring-petclinic-customers-service
  template:
    metadata:
      labels:
        app: spring-petclinic-customers-service
    spec:
      containers:
        - name: spring-petclinic-customers-service
          image: "{{ .Values.global.image.repository }}:{{ .Values.customers.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy | default "IfNotPresent" }}
          ports:
            - containerPort: 8081
          {{- if .Values.customers.env }}
          env:
            {{- range $key, $val := .Values.customers.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-customers-service
  labels:
    app: spring-petclinic-customers-service
spec:
  type: NodePort
  selector:
    app: spring-petclinic-customers-service
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: {{ .Values.customers.service.nodePort }}
{{- end }}
