global:
  image:
    repository: phbhuy19/spring-petclinic-microservices
    pullPolicy: IfNotPresent

# ====== 4 SERVICE CHÍNH ======

vets:
  enabled: true
  image:
    tag: main-spring-petclinic-vets-service-latest
  service:
    nodePort: 30081
  env:
    CONFIG_SERVER_URL: http://spring-petclinic-config-server:8888

visits:
  enabled: true
  image:
    tag: main-spring-petclinic-visits-service-latest
  service:
    nodePort: 30082
  env:
    CONFIG_SERVER_URL: http://spring-petclinic-config-server:8888

customers:
  enabled: true
  image:
    tag: main-spring-petclinic-customers-service-latest
  service:
    nodePort: 30083
  env:
    CONFIG_SERVER_URL: http://spring-petclinic-config-server:8888

genai:
  enabled: true
  image:
    tag: main-spring-petclinic-genai-service-latest
  service:
    nodePort: 30084
  env:
    CONFIG_SERVER_URL: http://spring-petclinic-config-server:8888
    OPENAI_API_KEY: YOUR_OPENAI_KEY
    AZURE_OPENAI_KEY: YOUR_AZURE_KEY
    AZURE_OPENAI_ENDPOINT: https://your-endpoint

# ====== HẠ TẦNG - GIỮ NGUYÊN TAG MAIN ======

configServer:
  enabled: true
  image:
    tag: main-spring-petclinic-config-server-latest
  service:
    nodePort: 30085

discoveryServer:
  enabled: true
  image:
    tag: main-spring-petclinic-discovery-server-latest
  service:
    nodePort: 30086

gateway:
  enabled: true
  image:
    tag: main-spring-petclinic-api-gateway-latest
  service:
    nodePort: 30087
  env:
    CONFIG_SERVER_URL: http://spring-petclinic-config-server:8888
    DISCOVERY_SERVER_URL: http://spring-petclinic-discovery-server:8761

adminServer:
  enabled: true
  image:
    tag: main-spring-petclinic-admin-server-latest
  service:
    nodePort: 30088

tracingServer:
  enabled: true
  replicaCount: 1
  image:
    repository: openzipkin/zipkin
    tag: latest
    pullPolicy: IfNotPresent
  env:
    STORAGE_TYPE: mem
  service:
    type: ClusterIP
    port: 30091
